

name: ci-test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [master]
jobs:
  test: 
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: changeme
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          -5433:5432

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: install golang-migrate
      run: | 
        curl -L  curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | sudo bash
        sudo apt-get update
        sudo apt-get install migrate

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test